name: Build Arduino Project

on:
    - push
    - pull_request

jobs:
    compile-sketch:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: arduino/compile-sketches@v1
              with:
                  sketch: './roboticArm.ino'
                  board: 'esp8266:esp8266:nodemcuv2'
                  build-properties: 'build.extra_flags=-DDEBUG'
                  output: 'compiled-sketch'

        
